<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-45D2DID" failures="2" tests="2" name="Test_reRun(failed)" time="0.14" errors="0" timestamp="2022-07-25T12:41:46 IST">
  <testcase classname="retryFailedTestCase.RetryDemo1" name="testCase2" time="0.033">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryFailedTestCase.RetryDemo1.testCase2(RetryDemo1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="retryFailedTestCase.RetryDemo1" name="testCase1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryFailedTestCase.RetryDemo1.testCase1(RetryDemo1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="retryFailedTestCase.RetryDemo1" name="testCase3" time="0.0">
    <ignored/>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- Test_reRun(failed) -->
